AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Rakefile
    - config.ru
    - Gemfile
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'app/api/**/*'
    - 'spec/features/**/*'
    - 'spec/requests/**/*'
    - 'spec/factories/*'
    - 'spec/models/*'

Metrics/ClassLength:
  Exclude:
    - 'app/api/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'app/api/**/*'
