default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     5
  template: template0

development:
  <<: *default
  database: share_knowledge_development

test:
  <<: *default
  database: share_knowledge_test

staging:
  <<: *default
  database: share_knowledge_staging

production:
  <<: *default
  database: share_knowledge_production
